### PR TITLE
Support Kurdish Wiktionary (ku) 

### PR DESCRIPTION
**Pull request by pamputt**
Bot has been tested on ku.wiktionary.org (see https://ku.wiktionary.org/wiki/W%C3%AEk%C3%AEferheng:D%C3%AEwan/2021#Lingualibre_bot) and is expected to be work properly).

### CODE REVIEW

**Comment by hugolpz** [comment]
@pamputt , can you tell us a bit about these commits.
@Poslovitch , what is the process to follow to accept the current PRs ?

**Comment by pamputt** [comment]
> @pamputt , can you tell us a bit about these commits.

I do not know what to say more. After the merge LinguaLibreBot will add (properly) audio pronunciations on the Kurdish Wiktionary.

**Comment by hugolpz** [comment]
@pamputt hello : ),
First, _Ideal_ github protocole requires a second coder to test a PR in real situation before the project accepts that PR. I'am not sure we have the human resources to do so tho.
Second, I think the bot got banned on wikidata or else recently, we need @Poslovitch's feedback on that.

**Comment by Poslovitch** [comment]
>  Second, I thing the bot got banned on wikidata or else recently, we need @Poslovitch's feedback on that.

No it isn't, see : https://www.wikidata.org/w/index.php?diff=1526275540

**Comment by pamputt** [comment]
The bot got the bot status (https://meta.wikimedia.org/wiki/Steward_requests/Bot_status#Lingua_Libre_Bot@kuwiktionary) so I think we can merge this branch and start to run the bot on kuwiktionary. I already performed tests before proposing this PR but I think it is better to star with a few recordings just to check that everything is still ok.

**Comment by Poslovitch** [comment]
Alright. I'm merging this, but this will be put in production by the weekend.
Thanks for your work!

**Comment by pamputt** [comment]
Thanks for the merge but it seems that the bot has never run on kuwikt (https://ku.wiktionary.org/wiki/Taybet:Be%C5%9Fdar%C3%AE/Lingua_Libre_Bot). Something wrong?

**Pull request merged**
