### PR TITLE
Add Odia Wiktionary (or) support

### PR DESCRIPTION
**Pull request by pamputt**
This is a working prototype for Odia language. On a test batch, it worked well (https://lingualibre.org/wiki/LinguaLibre:Bot#Working_prototype)

### CODE REVIEW

**Comment by hugolpz** [comment]
@pamputt , the commit conflict have been fixed.
I see nothing weird when reviewving.
Was this exact bot tested in real situation ?
(PS: please help my return from lilibreak, mentor welcome ^^)

**Comment by pamputt** [comment]
I tested the bot with my user account on or.wiktionary.org (see https://or.wiktionary.org/wiki/%E0%AC%AC%E0%AC%BF%E0%AC%B6%E0%AD%87%E0%AC%B7:%E0%AC%85%E0%AC%AC%E0%AC%A6%E0%AC%BE%E0%AC%A8/Pamputt). It has been validated by Psubhashish who did not report any error.

**Comment by Poslovitch** [comment]
So, I guess this is ready for merging?

**Comment by pamputt** [comment]
I asked Psubhashish (https://or.wiktionary.org/wiki/%E0%AC%AC%E0%AD%8D%E0%AD%9F%E0%AC%AC%E0%AC%B9%E0%AC%BE%E0%AC%B0%E0%AC%95%E0%AC%BE%E0%AC%B0%E0%AD%80:Psubhashish#Lingua_Libre_Bot) if they are ready for the bot to start adding pronunciations. Let us wait a few days to get his answer.

**Comment by hugolpz** [comment]
You seemed to suggest some kind procedure to respectfully activate a bot on a new Wiktionaries...

**Comment by psubhashish** [comment]
Hi everyone, I was not following this thread and the message on my user page (instead of talk page) did not signal any notification. I wish I had noticed this earlier. Anyway, I have responded as "yes" and clarifying here as well. We should definitely move forward for the LL Bot deployment.

**Comment by hugolpz** [comment]
Good to know, we should notify users better yes.
For ORI, [next steps forward are here](https://lingualibre.org/wiki/LinguaLibre:Bot#Bot_request_for_.7Bor.7D_witkionary).

**Review by psubhashish — APPROVED** [review]

**Comment by hugolpz** [comment]
Our python team is in pause. I'm unfamiliar with conflict resolution, python, and the bot.  Github asks me to edit that 👇🏼 .
@pamputt , @psubhashish what should I do ?
[EDIT:] I granted both of you higher userright on github so you can now handle that merge yourself.

image

**Comment by CedricTarbouriech** [comment]
Hi. I solved the merge conflict. I think it’s okay to merge.

**Comment by pamputt** [comment]
Thanks Cedric,
I will rework on orwiktionary.py later this week because it does not take into account the new LLbot structure. So I do not know yet whether the code works.

**Comment by psubhashish** [comment]
Thank you @hugolpz for taking this forward and thanks @CedricTarbouriech and @pamputt. I'll wait for @pamputt's update then.

**Pull request merged**
